# Site settings
title: OHBM Australia
email: ohbm.aus@gmail.com
description: "Uniting the Australian neuroimaging community" # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ohbm-aus.github.io" # the base hostname & protocol for your site

twitter_username: OHBM_Australia
github_username: OHBM-Aus

author: Sina Mansour L.

# Build settings
markdown: kramdown

# Permalink structure for posts
permalink: /posts/:title/

# Collections
collections:
  pages:
    output: true

# Jekyll plugins
plugins:
  - jekyll-sitemap
